In [2]:
import numpy as np 

In [3]:
l = [23245, 27, 546, 215, -1234]
a = np.array(l)
a

array([23245,    27,   546,   215, -1234])

In [4]:
a[2:]

array([  546,   215, -1234])

In [5]:
a[2:4]

array([546, 215])

In [7]:
b = a[2:4]    #It does not create a new array, it is only a view from a
b

array([546, 215])

In [8]:
b[0]

546

In [9]:
b[:]

array([546, 215])

In [11]:
b[:] = 111
b

array([111, 111])

In [13]:
a               # this is the fact, it changed the previous array

array([23245,    27,   111,   111, -1234])

To copy an array and properly take the segment of a previous array, we must use the copy() function

In [14]:
c = a.copy()
c

array([23245,    27,   111,   111, -1234])

In [15]:
c[0] = 0
c

array([    0,    27,   111,   111, -1234])

In [16]:
a

array([23245,    27,   111,   111, -1234])

---